# Basic Flutter linter rules with sensible defaults
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**, '**/*.g.dart', '**/*.freezed.dart']
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

# Developer-friendly linter rules
linter:
  rules:
    # Basic code quality
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    avoid_print: false  # Allow print for debugging
    
    # Type safety
    always_put_required_named_parameters_first: true
    avoid_dynamic_calls: true
    
    # Code organization
    sort_child_properties_last: true
    
    # Disable strict rules that might be too opinionated
    public_member_api_docs: false
    prefer_final_locals: false
    prefer_final_fields: false
    
    # Error prevention
    use_build_context_synchronously: true
    
    # Disable unnecessary rules
    unnecessary_this: false
    avoid_renaming_method_parameters: false
    avoid_void_async: true
    await_only_futures: true
    camel_case_types: true
    cancel_subscriptions: true
    cascade_invocations: true
    comment_references: true
    constant_identifier_names: false
    control_flow_in_finally: true
    curly_braces_in_flow_control_structures: true
    depend_on_referenced_packages: true
    deprecated_consistency: true
    empty_catches: true
    empty_constructor_bodies: true
    empty_statements: true
    file_names: true
    flutter_style_todos: true
    hash_and_equals: true
    implementation_imports: true
    join_return_with_assignment: true
    library_names: true
    library_prefixes: true
    lines_longer_than_80_chars: false
    literal_only_boolean_expressions: true
    missing_whitespace_between_adjacent_strings: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    no_runtimeType_toString: true
    non_constant_identifier_names: false
    null_check_on_nullable_type_parameter: true
    omit_local_variable_types: false
    one_member_abstracts: true
    only_throw_errors: true
    overridden_fields: true
    package_prefixed_library_names: true
    parameter_assignments: true
    prefer_adjacent_string_concatenation: true
    prefer_asserts_in_initializer_lists: true
    prefer_asserts_with_message: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
   
    prefer_const_declarations: true
    prefer_contains: true
    prefer_expression_function_bodies: true
  
    prefer_final_in_for_each: true
    prefer_foreach: true
    prefer_function_declarations_over_variables: true
    prefer_generic_function_type_aliases: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_inlined_adds: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_null_aware_operators: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true
    prefer_void_to_null: true
    provide_deprecation_message: true

    recursive_getters: true
    slash_for_doc_comments: true

    sort_constructors_first: true
    sort_pub_dependencies: true
    sort_unnamed_constructors_first: true
    test_types_in_equals: true
    throw_in_finally: true
    type_annotate_public_apis: true
    type_init_formals: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_constructor_name: true
    unnecessary_lambdas: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true

    unnecessary_to_list_in_spreads: true

    use_full_hex_values_for_flutter_colors: true
    use_function_type_syntax_for_parameters: true
    use_key_in_widget_constructors: true
    use_late_for_private_fields_and_variables: true
    use_named_constants: true
    use_rethrow_when_possible: true
    use_string_buffers: true
    use_super_parameters: true
    valid_regexps: true
    void_checks: true
